### ISSUE TITLE
Add round up

### ISSUE THREAD

**Issue by aschmois** [Litipk/php-bignumbers#10]
Right now, rounding a decimal will only round half up, I need a round up (ceiling). Looking through the code it seems that just changing the >= 5 to > 0 will make this happen.

**Comment by castarco** [comment]
Hello @aschmois , thanks for your bugreport.

Can you add an example of code, the expected output, and the current output? I'm not sure I'm correctly understanding the problem, and it would help having an example to add to the regression test in case a fix is needed.

**Comment by aschmois** [comment]
Sure, the innerRound method should allow a full up round instead of a half up round, which can be done by simply changing line 601 in the Decimal class from `if ($diffDigit >= 5) {` to `if ($diffDigit > 0) {`

The current result will round 3.14159 to 3.14 when setting the scale to 2, but I would like to be able to round full up (ceiling) so that the result is 3.15. The reasoning behind this is financial matters. When dealing with finances a very precise format needs to be used and all numbers are rounded up because a company will round up to the nearest cent, always.

**Comment by castarco** [comment]
Ok,

so maybe what is needed is to add a ceil method rather than modify the round method, no?

I think if we add a 'ceil' method then we need a 'floor' method too in order to have a consistent API.

**Comment by aschmois** [comment]
Correct, I see where the confusion went, that was my original thought :)

*Thank you,*
*Andres Schmois*
*Developer*

T 786-263-9122
E andresdroid@gmail.com
------------------------------------------
http://android305.com

**Comment by castarco** [comment]
Fixed in commit number 2f1d13e5a77009044143977d088fcabe78fc9916 .
