### ISSUE TITLE
Add trigonometric functions

### ISSUE THREAD

**Issue by castarco** [Litipk/php-bignumbers#13]
It would be nice to have the following trigonometric functions:

 * [X] sin : sine
 * [X] cos : cosine
 * [X] tan : tangent
 * [X] cotan : cotangent
 * [X] sec : secant
 * [X] cosec : cosecant
 * [X] arcsin : arcsine
 * [X] arccos : arccosine
 * [X] arctan : arctangent
 * [X] arccot : arccotangent
 * [X] arcsec : arcsecant
 * [X] arccsc : arccosecant

**Comment by castarco** [comment]
@stefanmajoor added `sin`, `cos` and `tan` methods, in the pull request #18 .

**Comment by punkka** [comment]
Hi, 

I would like to help on these functions but I'm not sure what process to follow as it would be my first participation to a project.

Could you give me some guidelines ?
I already worked on some fix for tan and on the implementation of cotan, sec and cosec.

Punkka.

**Comment by castarco** [comment]
Hi @punkka, if you want to contribute then you can clone the repository, commit changes and make a pull request to reintegrate it to the main project :) . 

If you add new features then is a good practice to add also unit tests to ensure we don't introduce new bugs (are you familiarized with unit testing?).

If you want to improve existing features then is desirable to attach comments explaining the improvements, benchmarks are also welcome.

Thanks for your interest! :)

**Comment by castarco** [comment]
Hi again @punkka, (i'm in the bus and i can't edit the previous message ^^U).

Some added comments:
 * All submited code will be automatically tested at TravisCI, but it's a good idea to previously test it locally with PHP-Unit.
 * It's a good idea to make a commit per feature/improvement/fix , better than doing big commits with a lot of changes.

**Comment by punkka** [comment]
Hi @castarco, 

Thank for all the advices.
I forked the repo and created a pull request.

**Comment by castarco** [comment]
Hi @codisart , as you can see, I'm merging your changes but I'm not contributing almost anything to the project this days.

I'm thinking on making a release with your changes (and throw away the current planned roadmap).
The reason is that I was wrong when I wanted to develop this library towards theoretical purposes.

I'll open a poll to all the contributors to see if we can drop "Infinite numbers" support (because infinite is only needed if you are working on theoretical problems or when your number representation is unable to represent a really big number... but we can!).

If everyone agrees on dropping infinite numbers support, the next step will be to extract the functions to function objects in order to simplify the code and making it more composable.

**Comment by codisart** [comment]
I'm okay with this plan. 
If you don't mind, I wish to continue to commit these functions, it is a good exercice for me.

**Comment by codisart** [comment]
Hi @castarco,

I was working on arccotangente and I came across this problem.
http://www.intmath.com/blog/mathematics/which-is-the-correct-graph-of-arccot-x-6009

As you can see, there are two ways to define this function.
Which one should we do implement ?
(I was working on the wikipedia definition : arccot(x) = Pi/2 - arctan(x) )

**Comment by yarwest** [comment]
Hello @castarco,

I forked this repo try and add some of the above-mentioned functions but I found that the checklist is out of date. Would be nice if this was kept up to date.

Thanks

**Comment by codisart** [comment]
Hello @yarwest,

The last ones were actually merged two weeks ago.
There are none left.

**Comment by yarwest** [comment]
Hence my reaction

**Comment by codisart** [comment]
Oh I got it now. Sorry mate.

**Comment by castarco** [comment]
Hi @codisart & @yarwest , I'm sorry about that. I'll update the checklist.

**Comment by castarco** [comment]
Done :) .
