### ISSUE TITLE
Add `isInteger` method to Decimal

### ISSUE THREAD

**Issue by castarco** [Litipk/php-bignumbers#21]
It's very useful to check if a number is an integer number in order to properly handle cases where we apply `pow` on negative numbers.

**Comment by punkka** [comment]
Hi,

I propose to check this condition with a regex. It would return false if a point was present in $this->value and if it was followed by a number different from 0 and true if not.

https://regex101.com/r/zH1vV5/1

**Comment by castarco** [comment]
Hi @punkka, I did it yesterday, in another branch (`TheBigInfiniteFix`), because I'm changing a lot of things.
